<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice {{ $invoice->invoice_reference }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        h1 {
            font-size: 18px;
            color: #222;
        }

        .header,
        .footer {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 8px;
        }

        th {
            background-color: #f5f5f5;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $invoice->organization->legal_name ?? 'Organization' }}</h1>
        <p>{{ $invoice->business->name ?? '' }}<br>
            Invoice Ref: <strong>{{ $invoice->invoice_reference }}</strong><br>
            Date: {{ $invoice->issue_date }}</p>
    </div>

    <h2>Bill To:</h2>
    <p>{{ $invoice->accounting_customer_party['party_name'] ?? 'Customer' }}<br>
        {{ $invoice->accounting_customer_party['email'] ?? '' }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Description</th>
                <th>Qty</th>
                <th>Unit Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($invoice->lines as $index => $line)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $line->item['name'] ?? '' }}</td>
                    <td>{{ $line->invoiced_quantity }}</td>
                    <td>{{ number_format($line->price['price_amount'] ?? 0, 2) }}</td>
                    <td>{{ number_format($line->line_extension_amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h3>Total Payable: ₦{{ number_format($invoice->legal_monetary_total['payable_amount'] ?? 0, 2) }}</h3>

    <div class="footer">
        <p>Generated by Vendra • {{ now()->format('Y-m-d H:i') }}</p>
    </div>
</body>

</html>
