apiVersion: v1
kind: Secret
metadata:
  name: lite-akraa-secret
  namespace: akraa
type: Opaque
stringData:
  APP_NAME: "Lite Akraa"  # IMPORTANT: Replace these values before deploying
  APP_KEY: "base64:rMA1kFhCPXftGIk6Q6icILiD1eh+vWXPJPjiSy9pBmc="  # Generate with: php artisan key:generate --show
  APP_URL: "https://lite.akraa.io"

  DB_USERNAME: "lite_akraa"
  DB_PASSWORD: "bxlbdF0WgmIP498KB1Ks/ch2Pis50cmS"
  MYSQL_ROOT_PASSWORD: "0J2ouyLgVMCSs5xq43gWd5N0X/V7a/1W"

  REDIS_PASSWORD: ""

  TAXLY_API_KEY: "43dbf9debb5bf81c2e952dc00d047b796de9f4dcf67decd19397f14af9f6d901"  # Taxly credentials for dev
  TAXLY_BASE_URL: "https://taxly.ng/api/v1"
  TAXLY_INTEGRATOR_SERVICE_ID: "109029"

  FIRS_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyU0xpdDRtb1RMbFdjd1A4eEp6RQp3ZTdkRHExdC9kMi9zcXdQTlNVandablFPbklabVh4TXY4QUQxemMxdUErZ3VCc2tpUGdoSXd6ekxWYXJoNk1KCndEdVUxSC95V2FPZE1PTnZOQy9OWERybXB5cE5WUDZyQnV3LzVjSERMdEtoZlJ0YkdFa1JSVVF4MVAxUUJ6REsKVVRpaTRJOXJld29zcVQ4V1dBOE8zRVd5ZHJ5TEg1K3JpVmRUNVBPeU1jcU95YUR2bGRqWG9ZdnBSTHlkcmtDQQpkUWpMdkw0bG00TVNxS05WdGVJR0Y4ZWk4M3Juck5wR3hKTVVGYVMwekt5TzBJZlY0alBCK3ZXN3I1TXdzTjRvCkRnWVR2ME85Q050N3JoNlEvYi9XR3Ewakl3WHJ3c3JIQXE4TXNyUVlGV0JIOHpmejMwOHRWMTlRM1hPTnEyWEMKMHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  FIRS_CERTIFICATE: "NklBL25zYU9QOGc3TXpRWStobE9WdlBQZlovbFIwM1hkdjlkNGI4UkNzQT0="

  MAIL_MAILER: "log"  # Mail settings (optional for dev)
  MAIL_HOST: ""
  MAIL_PORT: ""
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: ""
  MAIL_FROM_ADDRESS: "noreply@dev.yourdomain.com"
  MAIL_FROM_NAME: "${APP_NAME}"

  SESSION_SECURE_COOKIE: "true"  # Additional production settings
  SANCTUM_STATEFUL_DOMAINS: "https://lite.akraa.io"